server:
  port: 9002
spring:
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_NAME:localhost}:8761/eureka
